/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

module FA(a, b, ci, co, sum);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input a;
  input b;
  input ci;
  output co;
  output sum;
  NOT _20_ (
    .A(_13_),
    .Y(_15_)
  );
  NOT _21_ (
    .A(_03_),
    .Y(_17_)
  );
  NOT _22_ (
    .A(_04_),
    .Y(_18_)
  );
  NAND _23_ (
    .A(_18_),
    .B(_17_),
    .Y(_19_)
  );
  NAND _24_ (
    .A(_04_),
    .B(_03_),
    .Y(_05_)
  );
  NAND _25_ (
    .A(_05_),
    .B(_19_),
    .Y(_06_)
  );
  NOR _26_ (
    .A(_06_),
    .B(_15_),
    .Y(_07_)
  );
  NOR _27_ (
    .A(_04_),
    .B(_03_),
    .Y(_08_)
  );
  NOR _28_ (
    .A(_18_),
    .B(_17_),
    .Y(_09_)
  );
  NOR _29_ (
    .A(_09_),
    .B(_08_),
    .Y(_10_)
  );
  NOR _30_ (
    .A(_10_),
    .B(_13_),
    .Y(_11_)
  );
  NOR _31_ (
    .A(_11_),
    .B(_07_),
    .Y(_14_)
  );
  NAND _32_ (
    .A(_10_),
    .B(_13_),
    .Y(_12_)
  );
  NAND _33_ (
    .A(_12_),
    .B(_05_),
    .Y(_16_)
  );
  assign _03_ = ci;
  assign _04_ = a;
  assign _13_ = b;
  assign sum = _14_;
  assign co = _16_;
endmodule
