/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

module myFunc(a, b, c, d, w);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  input a;
  input b;
  input c;
  input d;
  output w;
  NOT _29_ (
    .A(_21_),
    .Y(_25_)
  );
  NOT _30_ (
    .A(_23_),
    .Y(_26_)
  );
  NOR _31_ (
    .A(_26_),
    .B(_25_),
    .Y(_27_)
  );
  NOT _32_ (
    .A(_24_),
    .Y(_28_)
  );
  NOR _33_ (
    .A(_28_),
    .B(_17_),
    .Y(_18_)
  );
  NAND _34_ (
    .A(_26_),
    .B(_25_),
    .Y(_19_)
  );
  NOR _35_ (
    .A(_19_),
    .B(_18_),
    .Y(_20_)
  );
  NOR _36_ (
    .A(_20_),
    .B(_27_),
    .Y(_22_)
  );
  assign _17_ = d;
  assign _21_ = a;
  assign _23_ = c;
  assign _24_ = b;
  assign w = _22_;
endmodule
